# Generated by Django 5.0.4 on 2024-04-22 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_character_discussionthread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussionthread',
            name='character',
        ),
        migrations.RemoveField(
            model_name='discussionthread',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='post',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='user',
        ),
        migrations.DeleteModel(
            name='Character',
        ),
        migrations.DeleteModel(
            name='DiscussionThread',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
