# Generated by Django 5.0.4 on 2024-04-22 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='text',
        ),
    ]
