# Generated by Django 5.0.4 on 2024-04-22 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_rename_content_comment_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='character',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Character',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
