# Generated by Django 5.0.4 on 2024-04-22 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
